oxnr/awesome-bigdata

- README.md
Monkey to Machine Learning and D3+ to data viz.
> Adding MonkeyLearn and D3Plus

- README.md
Adds GraphLab Create under the Machine Learning category.
> Add GraphLab Create

- README.md
- Fix links that are responding with 404's and forbidden
- Remove OHMData C5 as it is [acquired by WanDisco](http://www.computerworld.com/article/2686111/database/infinidb-goes-out-of-business-but-its-database-will-live-on-as-open-source.html) and its source is removed from [github](https://github.com/OhmData)
- Move Samza to Distributed Programming section as it is not a ingestion system but rather is a stream processing system like S4, Spark Streaming and Storm.
> Update README.md with potential link fixes

- README.md
StreamSets is a brand new open source (apache license) big-data ingest infrastructure with a simple to use drag and drop gui.
> Added StreamSets Data Collector

- README.md
Added Airbnb's Airpal, a Workflow Scheduler.
> Added Airflow Workflow Scheduler

- README.md
Hi, I added Apache REEF Project.
> Add Apache REEF project

- README.md
> Added BidMach to the list

- README.md
Skizze is a sketch data store to deal with all problems around counting and sketching using probabilistic data-structures.
> Add Skizze

- README.md
It's a new Apache incubation project for Google Dataflows and more.
> Add Apache Beam.

- README.md
> Bump H20 version

- README.md
Clojure based masterless, fault tolerant distributed computing.
> Add Onyx, fix typos

- README.md
Apache Eagle is an incubating project to enable a real time detection of malicious activities.
> Added Apache Eagle placed in the security section

- README.md
MOA is a variant of WEKA for big datasets. In fact, it is developed in the same University - Waikato, New Zealand.
> Added MOA Massive Online Analysis

- README.md
> adding TensorFlow

- README.md
Added section on books and in particular streaming related books. This is not all of the books but a start.
> Added section on books 

- README.md
- Druid
- Riak-TS
- Akumuli
- Rhombus
- Dalmatiner DB
- Blueflood
- Timely
> Updated Time-Series Databases List

- README.md
Added several more libraries with descriptions.
> Alphabetized the machine learning section

- README.md
> add baidu tera

- README.md
Built these (and some others already added) up over the course of summer.
> Add various links

- README.md
Caravel has been renamed to Superset.
> rename Caravel to Superset

- README.md
Lumify is an open source data integration, analytics, and visualization platform built to help you better understand your world of data.
> Added Lumify

- README.md
Added IndexR to Columnar Databases.
https://github.com/shunfei/indexr
> Added IndexR

- README.md
Pachyderm is a data lake that offers complete version control for data and leverages the container ecosystem to provide reproducible data processing.
> Add Pachyderm to this list

- README.md
Updated readme.md with the three technologies
> Add IBMStreams, Apache Edgent and streamsx.topology

- README.md
Added TimescaleDB and PipelineDB
> Added TimescaleDB and PipelineDB

- README.md
Hi,
I was wondering if you would consent to adding 3 books to your book list, all from Manning Publications: Spark in Action, Kafka Streams in Action, and Big Data. I believe that they are appropriate for your list.
Thank you for your consideration.
> Update README.md to include 3 books

- README.md
ATSD supports SQL and it's worth mentioning it in the short description given the fact that the database itself runs on top of the HBase key-value store. ATSD SQL docs: https://github.com/axibase/atsd/tree/master/api/sql#overview
> Add SQL capability to Axibase TSD

- README.md
Added SiriDB to time-series databases
> Added SiriDB to time-series databases

- README.md
Hi again,
I have one book and one free eBook which I think would be appropriate for your list.
Thanks for your consideration.
> One book and one free eBook to add to the book list

- README.md
> Added Apache NiFi to data ingestion section.

- README.md
Would you be willing to add the video course Spark in Motion to your resource article?
Thanks for your consideration.
> Add Spark Video

- README.md
I've added the *Distributed Index* section and Pilosa in it (since there wasn't a section which fits).
> Added Pilosa and Distributed Index section

- README.md
> Add LocustDB

- README.md
Added 3 awesome repositories on learning from graphs:
- graph embedding
- network embedding
- community detection
> Added awesome repos on learning from graphs.

- README.md
> Add JanusGraph to the list of graph databases.

- README.md
> Updated Links to Vega

- README.md
This includes Mara (https://github.com/mara/data-integration) in the list of Service Programming projects.
> Include Mara in Service Programming

- README.md
Please for your consideration if you would add this book to your book section.
Thank you
> Added Data Science at Scale with Python and Dask

- README.md
Hi, I thought this title might be a great addition to your list of books. Thank you for your consideration
> Added Graph-Powered Machine Learning

- README.md
We've just released our internal feature store, called Feast, which was jointly developed by GOJEK and Google.
> Added Feast (Feature Store)

- README.md
> Added Blazer

- README.md
> Added IronDB

- README.md
> Added jupyter

- README.md
> Added awesome-kafka

- README.md
I'm add the link to the DevExtreme React Chart.
> Add DevExtreme React Chart

- README.md
Add [dremio](https://www.dremio.com)
> Add Dremio

- README.md
Previous link went to a broken/empty index page
> fixed HCatalog link

- README.md
Added intermix.io - a performance monitoring dashboard for Amazon Redshift
> Added intermix.io

- README.md
Added faiss from facebook and annoy from spotify for memory optimised search. These frameworks are very helpful at a million or billion scale data searches
> Added new search engines/frameworks

- README.md
updated SpagoBI to Knowage  (they changed naming)
> Update link for SpagoBi project

- README.md
update latest link for spark streaming
> update latest link for spark streaming

- README.md
Karate Club consists of state-of-the-art methods to do unsupervised learning on graph structured data. To put it simply it is a Swiss Army knife for small-scale graph mining research. First, it provides network embedding techniques at the node and graph level. Second, it includes a variety of overlapping and non-overlapping community detection methods. Implemented methods cover a wide range of network science (NetSci, Complenet), data mining (ICDM, CIKM, KDD), artificial intelligence (AAAI, IJCAI) and machine learning (NeurIPS, ICML, ICLR) conferences, workshops, and pieces from prominent journals.
> Added Karate Club an unsupervised machine learning for graphs

- README.md
Links Removed (I believe don't add value):
- Apache Kiji
- Google Colossus
- Facebook Unicorn
- TeraGoogle
> Cleaning Broken Links

- README.md
Updating this to include Gazette which is a OSS for streaming
> Update to include Gazette

- README.md
Little Ball of Fur consists of methods that can sample from graph structured data. To put it simply it is a Swiss Army knife for graph sampling tasks. First, it includes a large variety of vertex, edge, and exploration sampling techniques. Second, it provides a unified application public interface which makes the application of sampling algorithms trivial for end-users. Implemented methods cover a wide range of networking (Networking, INFOCOM, SIGCOMM) and data mining (KDD, TKDD, ICDE) conferences, workshops, and pieces from prominent journals.
> Added Little Ball of Fur

- README.md
Hi,
I am Branko from Manning. I thought this liveVideo course of ours could be a good contribution for this list.
Thanks for considering it!
> Added Elasticsearch 7 and Elastic Stack

- README.md
Add Invantive SQL engine to real-time receive and analyze/replicate data from over 70 (cloud)platforms.
> Update README.md by SQL engine.

- README.md
* [Linkis](https://github.com/WeBankFinTech/Linkis)  - helps easily connect to various back-end computation/storage engines(Spark, Python, TiDB...), exposes various interfaces(REST, JDBC, Java ...), with multi-tenancy, high performance, and resource control.
* [DataSphere Studio](https://github.com/WeBankFinTech/DataSphereStudio)  - DataSphereStudio is a one stop data application development& management portal, covering scenarios including data exchange, desensitization/cleansing, analysis/mining, quality measurement, visualization, and task scheduling.
> It is recommended to increase computing middleware linkis and data application development portal DataSphere Studio

- README.md
Hey @onurakpolat 
removing a few broken links from the list!
Cheers!
> Removing some broken links

- README.md
Shapley is a Python library for evaluating binary classifiers in a machine learning ensemble.
The library consists of various methods to compute (approximate) the Shapley value of players (models) in weighted voting games (ensemble games). We covered widely know approximation methods from well known economics and computer science research papers. There are also functionalities to identify the heterogeneity of the player pool. In addition, the framework comes with a detailed documentation, 100% test coverage and illustrative toy examples.
> Added the Shapley framework

- README.md
I like the list you've compiled! I added a platform I'm working on which seemed appropriate in the applications category. Thanks for maintaining this resource.
> added HASH simulation platform

- README.md
Hi,
I am Branko from Manning Publications and I thought this new book of ours could be a good resource for the list on big data.
What do you think, is it a good match?
Thanks for considering it!
> added Azure Data Engineering

- README.md
> Adding dash(visualisation) and cronicle(scheduler)

- README.md
Added Census to the list of data ingestion tools. But really should be in a new category "Reverse-ETL"
> Added Census to the list

- README.md
Add Comet and Opik to Applications in README.md
Signed-off-by: Abby Morgan abigailm@comet.com
> Add Comet and Opik to README.md
